### ISSUE TITLE
modify docker for add mailhog

### ISSUE THREAD

**Issue by EkinL** [thierrymgn/shape-of-you#85]
# 📧 Configure MailHog in Docker

MailHog is a lightweight email testing tool that captures outgoing emails, allowing you to test email functionality in your local environment without sending real emails.

### 1️⃣ Add MailHog to `docker-compose.yml`

Modify your `compose.yml` file to include a MailHog service:

```yaml

mailhog:
  image: mailhog/mailhog
  ports:
    - "1025:1025"  # SMTP server
    - "8025:8025"  # Web UI
```

### 2️⃣ Configure Symfony to Use MailHog

Update your `.env` file to configure MailHog as the mailer transport:

```env
MAILER_DSN=smtp://mailhog:1025
```

### 4️⃣ Test MailHog

- Open your browser and navigate to: [http://localhost:8025](http://localhost:8025)
- Send a test email from your application and check if it appears in MailHog.

## ✅ Verifying the Setup

Run the following command to check if MailHog is running:

```sh
docker ps | grep mailhog
```

If you see a running container with MailHog, your setup is successful! 🎉
